export const ActionTypes = {
    LOGIN : "LOGIN",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAIL : "LOGIN_FAIL",
    GET_ROLES: "GET_ROLES",
    GET_ROLES_SUCCESS : "GET_ROLES_SUCCESS",
    GET_ROLES_FAIL: "GET_ROLES_FAIL",
    GET_USER_SUCCESSFULLY: "GET_USER_SUCCESSFULLY",
    EDIT_USER: "EDIT_USER",
    UPDATE_USER_SUCCESSFULLY : "UPDATE_USER_SUCCESSFULLY",
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    DELETE_USER_SUCCESSFULLY : 'DELETE_USER_SUCCESSFULLY',
    GET_PERMISSIONS_SUCCESS : "GET_PERMISSIONS_SUCCESS",
    ADD_COUNTRY_SUCCESS : "ADD_COUNTRY_SUCCESS",
    GET_ALL_COUNTRIES_SUCCESS : "GET_ALL_COUNTRIES_SUCCESS",
    UPDATE_COUNTRY_SUCCESSFULLY : "UPDATE_COUNTRY_SUCCESSFULLY",
    DELETE_COUNTRY_SUCCESSFULLY: "DELETE_COUNTRY_SUCCESSFULLY"
}